USE [master]
GO

/****** Object:  Database [MeubancoGrud]    Script Date: 06/06/2022 22:15:32 ******/
CREATE DATABASE [MeubancoGrud]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MeubancoGrud', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MeubancoGrud.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MeubancoGrud_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MeubancoGrud_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MeubancoGrud].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MeubancoGrud] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MeubancoGrud] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MeubancoGrud] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MeubancoGrud] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MeubancoGrud] SET ARITHABORT OFF 
GO

ALTER DATABASE [MeubancoGrud] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MeubancoGrud] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MeubancoGrud] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MeubancoGrud] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MeubancoGrud] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MeubancoGrud] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MeubancoGrud] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MeubancoGrud] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MeubancoGrud] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MeubancoGrud] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MeubancoGrud] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MeubancoGrud] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MeubancoGrud] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MeubancoGrud] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MeubancoGrud] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MeubancoGrud] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [MeubancoGrud] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MeubancoGrud] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MeubancoGrud] SET  MULTI_USER 
GO

ALTER DATABASE [MeubancoGrud] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MeubancoGrud] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MeubancoGrud] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MeubancoGrud] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MeubancoGrud] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MeubancoGrud] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MeubancoGrud] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MeubancoGrud] SET  READ_WRITE 
GO

